### ISSUE TITLE
Bazaar and Trade are mutually exclusive

### ISSUE THREAD

**Issue by oorzkws** [ImKyle4815/ArtifactEnsemble#2]
Enabling bazaar negates trade for the initial spawn. Is this intended?

**Comment by ImKyle4815** [comment]
I can't seem to reproduce this on my end, they appear to work together fine. Are you using any other mods?

**Comment by oorzkws** [comment]
Reproduced w/ no other mods, it seems fortune might have an effect.
![image](https://user-images.githubusercontent.com/65210810/159106835-e7b00ab7-3333-47af-b084-3e0fdc09502d.png)

p.s. Is it intentional that all the map choice portals in the shop are blank with this active?

edit: ran into it again
![image](https://user-images.githubusercontent.com/65210810/159109466-f828ef92-6a97-41f4-9221-e4a78fba15a0.png)

**Comment by oorzkws** [comment]
Resolved by latest commit.
