### ISSUE TITLE
Some combinations result in game not loading

### ISSUE THREAD

**Issue by oorzkws** [ImKyle4815/ArtifactEnsemble#3]
I'll add as I run into them.

- Summit + Trade + [Vanilla]Sacrifice + [Vanilla]Swarms

Works once but not after quitting the run:
- To be added

**Comment by ImKyle4815** [comment]
Does this occur consistently or only some of the time? After a few tests my game seemed to work fine.

**Comment by oorzkws** [comment]
Some of the time. Sometimes it's the first run I try, sometimes it's the second or third with the same combo that worked on the first

**Comment by oorzkws** [comment]
![image](https://user-images.githubusercontent.com/65210810/159106572-90631fbf-0df3-496f-b7aa-f63344fa84fb.png)
With this set, I started a run, died intentionally on the first level, and then the game got stuck at a black screen after hitting ready for a second try

Second time, I did a run with just bazaar and trade to see if I could reproduce the other issue. I immediately exited to menu then started a new run with the following and got stuck at a black screen after readying.
![image](https://user-images.githubusercontent.com/65210810/159106754-2a8beb57-7f85-409f-ad0f-72ca81d58e94.png)

**Comment by oorzkws** [comment]
Maybe related, caught this in the log before the game locked up
```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ArtifactEnsemble.ArtifactTemplate.Enabled () (at <4c5874ebda75494a9ee3f533d08c3a10>:IL_0011)
ArtifactEnsemble.Artifacts.TradeArtifact.ForceBluePortal (On.RoR2.TeleporterInteraction+orig_AttemptToSpawnAllEligiblePortals orig, RoR2.TeleporterInteraction self) (at <4c5874ebda75494a9ee3f533d08c3a10>:IL_0001)
DMD<>?254518784.Hook<RoR2.TeleporterInteraction::AttemptToSpawnAllEligiblePortals>?-1779014144 (RoR2.TeleporterInteraction ) (at <09b4fa88549b4df4bdbcd13950b171b7>:IL_0014)
RoR2.TeleporterInteraction+ChargedState.OnEnter () (at <0f44b36eaa194934bb127b3fdd08e444>:IL_0035)
RoR2.EntityStateMachine.SetState (EntityStates.EntityState newState) (at <0f44b36eaa194934bb127b3fdd08e444>:IL_005C)
RoR2.EntityStateMachine.FixedUpdate () (at <0f44b36eaa194934bb127b3fdd08e444>:IL_0008)
```
